sudo: required
services:
  - docker

before_install:

  - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-x86_64 > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build

  - # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - wget http://download.osgeo.org/geos/geos-3.4.2.tar.bz2
  - tar xjf geos-3.4.2.tar.bz2
  - cd geos-3.4.2
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
- docker-compose run -e SKIP_DJANGO_MIGRATE=1 -e GOOGLE_KEY=$GOOGLE_KEY web python manage.py test -k -v 3
